/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.webots.validation;

import fr.unice.polytech.si5.webots.validation.AbstractPolycreateValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PolycreateValidator extends AbstractPolycreateValidator {
}
