/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.webots.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class PolycreateGrammarAccess extends AbstractGrammarElementFinder {
	
	public class RobotProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.si5.webots.Polycreate.RobotProgram");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRobotProgramAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRobotProgramKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cInitialStateAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cInitialStateStateParserRuleCall_4_0 = (RuleCall)cInitialStateAssignment_4.eContents().get(0);
		private final Assignment cOwnedStatesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cOwnedStatesStateParserRuleCall_5_0 = (RuleCall)cOwnedStatesAssignment_5.eContents().get(0);
		private final Assignment cGlobalTransitionsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cGlobalTransitionsTransitionParserRuleCall_6_0 = (RuleCall)cGlobalTransitionsAssignment_6.eContents().get(0);
		
		//RobotProgram:
		//	{RobotProgram}
		//	'RobotProgram'
		//	name=EString
		//	'->' initialState=State
		//	ownedStates+=State*
		//	globalTransitions+=Transition*;
		@Override public ParserRule getRule() { return rule; }
		
		//{RobotProgram} 'RobotProgram' name=EString '->' initialState=State ownedStates+=State* globalTransitions+=Transition*
		public Group getGroup() { return cGroup; }
		
		//{RobotProgram}
		public Action getRobotProgramAction_0() { return cRobotProgramAction_0; }
		
		//'RobotProgram'
		public Keyword getRobotProgramKeyword_1() { return cRobotProgramKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_3() { return cHyphenMinusGreaterThanSignKeyword_3; }
		
		//initialState=State
		public Assignment getInitialStateAssignment_4() { return cInitialStateAssignment_4; }
		
		//State
		public RuleCall getInitialStateStateParserRuleCall_4_0() { return cInitialStateStateParserRuleCall_4_0; }
		
		//ownedStates+=State*
		public Assignment getOwnedStatesAssignment_5() { return cOwnedStatesAssignment_5; }
		
		//State
		public RuleCall getOwnedStatesStateParserRuleCall_5_0() { return cOwnedStatesStateParserRuleCall_5_0; }
		
		//globalTransitions+=Transition*
		public Assignment getGlobalTransitionsAssignment_6() { return cGlobalTransitionsAssignment_6; }
		
		//Transition
		public RuleCall getGlobalTransitionsTransitionParserRuleCall_6_0() { return cGlobalTransitionsTransitionParserRuleCall_6_0; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.si5.webots.Polycreate.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class ConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.si5.webots.Polycreate.Condition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSimpleConditionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cObjectConditionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Condition:
		//	SimpleCondition | ObjectCondition;
		@Override public ParserRule getRule() { return rule; }
		
		//SimpleCondition | ObjectCondition
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SimpleCondition
		public RuleCall getSimpleConditionParserRuleCall_0() { return cSimpleConditionParserRuleCall_0; }
		
		//ObjectCondition
		public RuleCall getObjectConditionParserRuleCall_1() { return cObjectConditionParserRuleCall_1; }
	}
	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.si5.webots.Polycreate.Action");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMoveActionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTurnActionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Action:
		//	MoveAction | TurnAction;
		@Override public ParserRule getRule() { return rule; }
		
		//MoveAction | TurnAction
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MoveAction
		public RuleCall getMoveActionParserRuleCall_0() { return cMoveActionParserRuleCall_0; }
		
		//TurnAction
		public RuleCall getTurnActionParserRuleCall_1() { return cTurnActionParserRuleCall_1; }
	}
	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.si5.webots.Polycreate.Transition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTransitionAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cConditionsAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cConditionsConditionParserRuleCall_1_0_0 = (RuleCall)cConditionsAssignment_1_0.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Keyword cAndKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Assignment cConditionsAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final RuleCall cConditionsConditionParserRuleCall_1_1_1_0 = (RuleCall)cConditionsAssignment_1_1_1.eContents().get(0);
		private final Keyword cEqualsSignGreaterThanSignKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Assignment cNextStateAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cNextStateStateCrossReference_2_0 = (CrossReference)cNextStateAssignment_2.eContents().get(0);
		private final RuleCall cNextStateStateEStringParserRuleCall_2_0_1 = (RuleCall)cNextStateStateCrossReference_2_0.eContents().get(1);
		
		//Transition:
		//	{Transition} (conditions+=Condition ('and' conditions+=Condition)* '=>')? nextState=[State|EString];
		@Override public ParserRule getRule() { return rule; }
		
		//{Transition} (conditions+=Condition ('and' conditions+=Condition)* '=>')? nextState=[State|EString]
		public Group getGroup() { return cGroup; }
		
		//{Transition}
		public Action getTransitionAction_0() { return cTransitionAction_0; }
		
		//(conditions+=Condition ('and' conditions+=Condition)* '=>')?
		public Group getGroup_1() { return cGroup_1; }
		
		//conditions+=Condition
		public Assignment getConditionsAssignment_1_0() { return cConditionsAssignment_1_0; }
		
		//Condition
		public RuleCall getConditionsConditionParserRuleCall_1_0_0() { return cConditionsConditionParserRuleCall_1_0_0; }
		
		//('and' conditions+=Condition)*
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//'and'
		public Keyword getAndKeyword_1_1_0() { return cAndKeyword_1_1_0; }
		
		//conditions+=Condition
		public Assignment getConditionsAssignment_1_1_1() { return cConditionsAssignment_1_1_1; }
		
		//Condition
		public RuleCall getConditionsConditionParserRuleCall_1_1_1_0() { return cConditionsConditionParserRuleCall_1_1_1_0; }
		
		//'=>'
		public Keyword getEqualsSignGreaterThanSignKeyword_1_2() { return cEqualsSignGreaterThanSignKeyword_1_2; }
		
		//nextState=[State|EString]
		public Assignment getNextStateAssignment_2() { return cNextStateAssignment_2; }
		
		//[State|EString]
		public CrossReference getNextStateStateCrossReference_2_0() { return cNextStateStateCrossReference_2_0; }
		
		//EString
		public RuleCall getNextStateStateEStringParserRuleCall_2_0_1() { return cNextStateStateEStringParserRuleCall_2_0_1; }
	}
	public class StateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.si5.webots.Polycreate.State");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStateAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStateKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cActionsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cEqualsSignKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		private final Assignment cActionsAssignment_4_3 = (Assignment)cGroup_4.eContents().get(3);
		private final RuleCall cActionsActionParserRuleCall_4_3_0 = (RuleCall)cActionsAssignment_4_3.eContents().get(0);
		private final Group cGroup_4_4 = (Group)cGroup_4.eContents().get(4);
		private final Keyword cCommaKeyword_4_4_0 = (Keyword)cGroup_4_4.eContents().get(0);
		private final Assignment cActionsAssignment_4_4_1 = (Assignment)cGroup_4_4.eContents().get(1);
		private final RuleCall cActionsActionParserRuleCall_4_4_1_0 = (RuleCall)cActionsAssignment_4_4_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_4_5 = (Keyword)cGroup_4.eContents().get(5);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTransitionsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cEqualsSignKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Assignment cTransitionsAssignment_5_3 = (Assignment)cGroup_5.eContents().get(3);
		private final RuleCall cTransitionsTransitionParserRuleCall_5_3_0 = (RuleCall)cTransitionsAssignment_5_3.eContents().get(0);
		private final Group cGroup_5_4 = (Group)cGroup_5.eContents().get(4);
		private final Keyword cCommaKeyword_5_4_0 = (Keyword)cGroup_5_4.eContents().get(0);
		private final Assignment cTransitionsAssignment_5_4_1 = (Assignment)cGroup_5_4.eContents().get(1);
		private final RuleCall cTransitionsTransitionParserRuleCall_5_4_1_0 = (RuleCall)cTransitionsAssignment_5_4_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_5_5 = (Keyword)cGroup_5.eContents().get(5);
		
		//State:
		//	{State}
		//	'State' name=EString
		//	':' ('actions' '=' '[' actions+=Action (',' actions+=Action)* ']')? ('transitions' '=' '[' transitions+=Transition
		//	("," transitions+=Transition)* ']')?;
		@Override public ParserRule getRule() { return rule; }
		
		//{State} 'State' name=EString ':' ('actions' '=' '[' actions+=Action (',' actions+=Action)* ']')? ('transitions' '=' '['
		//transitions+=Transition ("," transitions+=Transition)* ']')?
		public Group getGroup() { return cGroup; }
		
		//{State}
		public Action getStateAction_0() { return cStateAction_0; }
		
		//'State'
		public Keyword getStateKeyword_1() { return cStateKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//('actions' '=' '[' actions+=Action (',' actions+=Action)* ']')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'actions'
		public Keyword getActionsKeyword_4_0() { return cActionsKeyword_4_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_4_1() { return cEqualsSignKeyword_4_1; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_4_2() { return cLeftSquareBracketKeyword_4_2; }
		
		//actions+=Action
		public Assignment getActionsAssignment_4_3() { return cActionsAssignment_4_3; }
		
		//Action
		public RuleCall getActionsActionParserRuleCall_4_3_0() { return cActionsActionParserRuleCall_4_3_0; }
		
		//(',' actions+=Action)*
		public Group getGroup_4_4() { return cGroup_4_4; }
		
		//','
		public Keyword getCommaKeyword_4_4_0() { return cCommaKeyword_4_4_0; }
		
		//actions+=Action
		public Assignment getActionsAssignment_4_4_1() { return cActionsAssignment_4_4_1; }
		
		//Action
		public RuleCall getActionsActionParserRuleCall_4_4_1_0() { return cActionsActionParserRuleCall_4_4_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_4_5() { return cRightSquareBracketKeyword_4_5; }
		
		//('transitions' '=' '[' transitions+=Transition ("," transitions+=Transition)* ']')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'transitions'
		public Keyword getTransitionsKeyword_5_0() { return cTransitionsKeyword_5_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_5_1() { return cEqualsSignKeyword_5_1; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_5_2() { return cLeftSquareBracketKeyword_5_2; }
		
		//transitions+=Transition
		public Assignment getTransitionsAssignment_5_3() { return cTransitionsAssignment_5_3; }
		
		//Transition
		public RuleCall getTransitionsTransitionParserRuleCall_5_3_0() { return cTransitionsTransitionParserRuleCall_5_3_0; }
		
		//("," transitions+=Transition)*
		public Group getGroup_5_4() { return cGroup_5_4; }
		
		//","
		public Keyword getCommaKeyword_5_4_0() { return cCommaKeyword_5_4_0; }
		
		//transitions+=Transition
		public Assignment getTransitionsAssignment_5_4_1() { return cTransitionsAssignment_5_4_1; }
		
		//Transition
		public RuleCall getTransitionsTransitionParserRuleCall_5_4_1_0() { return cTransitionsTransitionParserRuleCall_5_4_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_5_5() { return cRightSquareBracketKeyword_5_5; }
	}
	public class SimpleConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.si5.webots.Polycreate.SimpleCondition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSimpleConditionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDetectKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cDetectionTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDetectionTypeDETECTIONEnumRuleCall_2_0 = (RuleCall)cDetectionTypeAssignment_2.eContents().get(0);
		
		//SimpleCondition:
		//	{SimpleCondition}
		//	'detect' detectionType=DETECTION;
		@Override public ParserRule getRule() { return rule; }
		
		//{SimpleCondition} 'detect' detectionType=DETECTION
		public Group getGroup() { return cGroup; }
		
		//{SimpleCondition}
		public Action getSimpleConditionAction_0() { return cSimpleConditionAction_0; }
		
		//'detect'
		public Keyword getDetectKeyword_1() { return cDetectKeyword_1; }
		
		//detectionType=DETECTION
		public Assignment getDetectionTypeAssignment_2() { return cDetectionTypeAssignment_2; }
		
		//DETECTION
		public RuleCall getDetectionTypeDETECTIONEnumRuleCall_2_0() { return cDetectionTypeDETECTIONEnumRuleCall_2_0; }
	}
	public class ObjectConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.si5.webots.Polycreate.ObjectCondition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cDistanceConditionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAngleConditionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ObjectCondition:
		//	DistanceCondition | AngleCondition;
		@Override public ParserRule getRule() { return rule; }
		
		//DistanceCondition | AngleCondition
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//DistanceCondition
		public RuleCall getDistanceConditionParserRuleCall_0() { return cDistanceConditionParserRuleCall_0; }
		
		//AngleCondition
		public RuleCall getAngleConditionParserRuleCall_1() { return cAngleConditionParserRuleCall_1; }
	}
	public class DistanceConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.si5.webots.Polycreate.DistanceCondition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDistanceConditionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDetectKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cObjectKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCameraTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCameraTypeCAMERATYPEEnumRuleCall_3_0 = (RuleCall)cCameraTypeAssignment_3.eContents().get(0);
		private final Keyword cWithKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cDistanceKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLessThanSignKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cDistanceAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cDistanceEDoubleParserRuleCall_7_0 = (RuleCall)cDistanceAssignment_7.eContents().get(0);
		
		//DistanceCondition:
		//	{DistanceCondition}
		//	'detect' 'object' cameraType=CAMERATYPE 'with' 'distance' '<' distance=EDouble;
		@Override public ParserRule getRule() { return rule; }
		
		//{DistanceCondition} 'detect' 'object' cameraType=CAMERATYPE 'with' 'distance' '<' distance=EDouble
		public Group getGroup() { return cGroup; }
		
		//{DistanceCondition}
		public Action getDistanceConditionAction_0() { return cDistanceConditionAction_0; }
		
		//'detect'
		public Keyword getDetectKeyword_1() { return cDetectKeyword_1; }
		
		//'object'
		public Keyword getObjectKeyword_2() { return cObjectKeyword_2; }
		
		//cameraType=CAMERATYPE
		public Assignment getCameraTypeAssignment_3() { return cCameraTypeAssignment_3; }
		
		//CAMERATYPE
		public RuleCall getCameraTypeCAMERATYPEEnumRuleCall_3_0() { return cCameraTypeCAMERATYPEEnumRuleCall_3_0; }
		
		//'with'
		public Keyword getWithKeyword_4() { return cWithKeyword_4; }
		
		//'distance'
		public Keyword getDistanceKeyword_5() { return cDistanceKeyword_5; }
		
		//'<'
		public Keyword getLessThanSignKeyword_6() { return cLessThanSignKeyword_6; }
		
		//distance=EDouble
		public Assignment getDistanceAssignment_7() { return cDistanceAssignment_7; }
		
		//EDouble
		public RuleCall getDistanceEDoubleParserRuleCall_7_0() { return cDistanceEDoubleParserRuleCall_7_0; }
	}
	public class AngleConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.si5.webots.Polycreate.AngleCondition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAngleConditionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDetectKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cObjectKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCameraTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCameraTypeCAMERATYPEEnumRuleCall_3_0 = (RuleCall)cCameraTypeAssignment_3.eContents().get(0);
		private final Keyword cWithKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cAngleKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLessThanSignKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cAngleAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cAngleEDoubleParserRuleCall_7_0 = (RuleCall)cAngleAssignment_7.eContents().get(0);
		
		//AngleCondition:
		//	{AngleCondition}
		//	'detect' 'object' cameraType=CAMERATYPE 'with' 'angle' '<' angle=EDouble;
		@Override public ParserRule getRule() { return rule; }
		
		//{AngleCondition} 'detect' 'object' cameraType=CAMERATYPE 'with' 'angle' '<' angle=EDouble
		public Group getGroup() { return cGroup; }
		
		//{AngleCondition}
		public Action getAngleConditionAction_0() { return cAngleConditionAction_0; }
		
		//'detect'
		public Keyword getDetectKeyword_1() { return cDetectKeyword_1; }
		
		//'object'
		public Keyword getObjectKeyword_2() { return cObjectKeyword_2; }
		
		//cameraType=CAMERATYPE
		public Assignment getCameraTypeAssignment_3() { return cCameraTypeAssignment_3; }
		
		//CAMERATYPE
		public RuleCall getCameraTypeCAMERATYPEEnumRuleCall_3_0() { return cCameraTypeCAMERATYPEEnumRuleCall_3_0; }
		
		//'with'
		public Keyword getWithKeyword_4() { return cWithKeyword_4; }
		
		//'angle'
		public Keyword getAngleKeyword_5() { return cAngleKeyword_5; }
		
		//'<'
		public Keyword getLessThanSignKeyword_6() { return cLessThanSignKeyword_6; }
		
		//angle=EDouble
		public Assignment getAngleAssignment_7() { return cAngleAssignment_7; }
		
		//EDouble
		public RuleCall getAngleEDoubleParserRuleCall_7_0() { return cAngleEDoubleParserRuleCall_7_0; }
	}
	public class MoveActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.si5.webots.Polycreate.MoveAction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMoveActionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMoveKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cDirectionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDirectionDIRECTIONEnumRuleCall_2_0 = (RuleCall)cDirectionAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDuringKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDurationAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDurationEDoubleParserRuleCall_3_1_0 = (RuleCall)cDurationAssignment_3_1.eContents().get(0);
		
		//MoveAction:
		//	{MoveAction}
		//	'move' direction=DIRECTION ('during' duration=EDouble)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{MoveAction} 'move' direction=DIRECTION ('during' duration=EDouble)?
		public Group getGroup() { return cGroup; }
		
		//{MoveAction}
		public Action getMoveActionAction_0() { return cMoveActionAction_0; }
		
		//'move'
		public Keyword getMoveKeyword_1() { return cMoveKeyword_1; }
		
		//direction=DIRECTION
		public Assignment getDirectionAssignment_2() { return cDirectionAssignment_2; }
		
		//DIRECTION
		public RuleCall getDirectionDIRECTIONEnumRuleCall_2_0() { return cDirectionDIRECTIONEnumRuleCall_2_0; }
		
		//('during' duration=EDouble)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'during'
		public Keyword getDuringKeyword_3_0() { return cDuringKeyword_3_0; }
		
		//duration=EDouble
		public Assignment getDurationAssignment_3_1() { return cDurationAssignment_3_1; }
		
		//EDouble
		public RuleCall getDurationEDoubleParserRuleCall_3_1_0() { return cDurationEDoubleParserRuleCall_3_1_0; }
	}
	public class TurnActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.si5.webots.Polycreate.TurnAction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTurnActionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTurnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cAngleAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAngleEDoubleParserRuleCall_2_0 = (RuleCall)cAngleAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDuringKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDurationAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDurationEDoubleParserRuleCall_3_1_0 = (RuleCall)cDurationAssignment_3_1.eContents().get(0);
		
		//TurnAction:
		//	{TurnAction}
		//	'turn' angle=EDouble ('during' duration=EDouble)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{TurnAction} 'turn' angle=EDouble ('during' duration=EDouble)?
		public Group getGroup() { return cGroup; }
		
		//{TurnAction}
		public Action getTurnActionAction_0() { return cTurnActionAction_0; }
		
		//'turn'
		public Keyword getTurnKeyword_1() { return cTurnKeyword_1; }
		
		//angle=EDouble
		public Assignment getAngleAssignment_2() { return cAngleAssignment_2; }
		
		//EDouble
		public RuleCall getAngleEDoubleParserRuleCall_2_0() { return cAngleEDoubleParserRuleCall_2_0; }
		
		//('during' duration=EDouble)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'during'
		public Keyword getDuringKeyword_3_0() { return cDuringKeyword_3_0; }
		
		//duration=EDouble
		public Assignment getDurationAssignment_3_1() { return cDurationAssignment_3_1; }
		
		//EDouble
		public RuleCall getDurationEDoubleParserRuleCall_3_1_0() { return cDurationEDoubleParserRuleCall_3_1_0; }
	}
	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.si5.webots.Polycreate.EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDouble ecore::EDouble:
		//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E' | 'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E' | 'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'E' | 'e'
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	
	public class DETECTIONElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.si5.webots.Polycreate.DETECTION");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCOLLISION_LEFTEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCOLLISION_LEFTCOLLISION_LEFTKeyword_0_0 = (Keyword)cCOLLISION_LEFTEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCOLLISION_RIGHTEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCOLLISION_RIGHTCOLLISION_RIGHTKeyword_1_0 = (Keyword)cCOLLISION_RIGHTEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cVIRTUAL_WALLEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cVIRTUAL_WALLVIRTUAL_WALLKeyword_2_0 = (Keyword)cVIRTUAL_WALLEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cCLIFF_LEFTEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cCLIFF_LEFTCLIFF_LEFTKeyword_3_0 = (Keyword)cCLIFF_LEFTEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cCLIFF_RIGHTEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cCLIFF_RIGHTCLIFF_RIGHTKeyword_4_0 = (Keyword)cCLIFF_RIGHTEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cCLIFF_FRONTEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cCLIFF_FRONTCLIFF_FRONTKeyword_5_0 = (Keyword)cCLIFF_FRONTEnumLiteralDeclaration_5.eContents().get(0);
		
		//enum DETECTION:
		//	COLLISION_LEFT | COLLISION_RIGHT | VIRTUAL_WALL | CLIFF_LEFT | CLIFF_RIGHT | CLIFF_FRONT;
		public EnumRule getRule() { return rule; }
		
		//COLLISION_LEFT | COLLISION_RIGHT | VIRTUAL_WALL | CLIFF_LEFT | CLIFF_RIGHT | CLIFF_FRONT
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//COLLISION_LEFT
		public EnumLiteralDeclaration getCOLLISION_LEFTEnumLiteralDeclaration_0() { return cCOLLISION_LEFTEnumLiteralDeclaration_0; }
		
		//'COLLISION_LEFT'
		public Keyword getCOLLISION_LEFTCOLLISION_LEFTKeyword_0_0() { return cCOLLISION_LEFTCOLLISION_LEFTKeyword_0_0; }
		
		//COLLISION_RIGHT
		public EnumLiteralDeclaration getCOLLISION_RIGHTEnumLiteralDeclaration_1() { return cCOLLISION_RIGHTEnumLiteralDeclaration_1; }
		
		//'COLLISION_RIGHT'
		public Keyword getCOLLISION_RIGHTCOLLISION_RIGHTKeyword_1_0() { return cCOLLISION_RIGHTCOLLISION_RIGHTKeyword_1_0; }
		
		//VIRTUAL_WALL
		public EnumLiteralDeclaration getVIRTUAL_WALLEnumLiteralDeclaration_2() { return cVIRTUAL_WALLEnumLiteralDeclaration_2; }
		
		//'VIRTUAL_WALL'
		public Keyword getVIRTUAL_WALLVIRTUAL_WALLKeyword_2_0() { return cVIRTUAL_WALLVIRTUAL_WALLKeyword_2_0; }
		
		//CLIFF_LEFT
		public EnumLiteralDeclaration getCLIFF_LEFTEnumLiteralDeclaration_3() { return cCLIFF_LEFTEnumLiteralDeclaration_3; }
		
		//'CLIFF_LEFT'
		public Keyword getCLIFF_LEFTCLIFF_LEFTKeyword_3_0() { return cCLIFF_LEFTCLIFF_LEFTKeyword_3_0; }
		
		//CLIFF_RIGHT
		public EnumLiteralDeclaration getCLIFF_RIGHTEnumLiteralDeclaration_4() { return cCLIFF_RIGHTEnumLiteralDeclaration_4; }
		
		//'CLIFF_RIGHT'
		public Keyword getCLIFF_RIGHTCLIFF_RIGHTKeyword_4_0() { return cCLIFF_RIGHTCLIFF_RIGHTKeyword_4_0; }
		
		//CLIFF_FRONT
		public EnumLiteralDeclaration getCLIFF_FRONTEnumLiteralDeclaration_5() { return cCLIFF_FRONTEnumLiteralDeclaration_5; }
		
		//'CLIFF_FRONT'
		public Keyword getCLIFF_FRONTCLIFF_FRONTKeyword_5_0() { return cCLIFF_FRONTCLIFF_FRONTKeyword_5_0; }
	}
	public class DIRECTIONElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.si5.webots.Polycreate.DIRECTION");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cFORWARDEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cFORWARDFORWARDKeyword_0_0 = (Keyword)cFORWARDEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBACKWARDEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBACKWARDBACKWARDKeyword_1_0 = (Keyword)cBACKWARDEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum DIRECTION:
		//	FORWARD | BACKWARD;
		public EnumRule getRule() { return rule; }
		
		//FORWARD | BACKWARD
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FORWARD
		public EnumLiteralDeclaration getFORWARDEnumLiteralDeclaration_0() { return cFORWARDEnumLiteralDeclaration_0; }
		
		//'FORWARD'
		public Keyword getFORWARDFORWARDKeyword_0_0() { return cFORWARDFORWARDKeyword_0_0; }
		
		//BACKWARD
		public EnumLiteralDeclaration getBACKWARDEnumLiteralDeclaration_1() { return cBACKWARDEnumLiteralDeclaration_1; }
		
		//'BACKWARD'
		public Keyword getBACKWARDBACKWARDKeyword_1_0() { return cBACKWARDBACKWARDKeyword_1_0; }
	}
	public class CAMERATYPEElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.si5.webots.Polycreate.CAMERATYPE");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cBACKEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cBACKBACKKeyword_0_0 = (Keyword)cBACKEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFRONTEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFRONTFRONTKeyword_1_0 = (Keyword)cFRONTEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum CAMERATYPE:
		//	BACK | FRONT;
		public EnumRule getRule() { return rule; }
		
		//BACK | FRONT
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//BACK
		public EnumLiteralDeclaration getBACKEnumLiteralDeclaration_0() { return cBACKEnumLiteralDeclaration_0; }
		
		//'BACK'
		public Keyword getBACKBACKKeyword_0_0() { return cBACKBACKKeyword_0_0; }
		
		//FRONT
		public EnumLiteralDeclaration getFRONTEnumLiteralDeclaration_1() { return cFRONTEnumLiteralDeclaration_1; }
		
		//'FRONT'
		public Keyword getFRONTFRONTKeyword_1_0() { return cFRONTFRONTKeyword_1_0; }
	}
	
	private final RobotProgramElements pRobotProgram;
	private final EStringElements pEString;
	private final ConditionElements pCondition;
	private final ActionElements pAction;
	private final TransitionElements pTransition;
	private final StateElements pState;
	private final SimpleConditionElements pSimpleCondition;
	private final ObjectConditionElements pObjectCondition;
	private final DistanceConditionElements pDistanceCondition;
	private final AngleConditionElements pAngleCondition;
	private final DETECTIONElements eDETECTION;
	private final MoveActionElements pMoveAction;
	private final TurnActionElements pTurnAction;
	private final DIRECTIONElements eDIRECTION;
	private final CAMERATYPEElements eCAMERATYPE;
	private final EDoubleElements pEDouble;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public PolycreateGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRobotProgram = new RobotProgramElements();
		this.pEString = new EStringElements();
		this.pCondition = new ConditionElements();
		this.pAction = new ActionElements();
		this.pTransition = new TransitionElements();
		this.pState = new StateElements();
		this.pSimpleCondition = new SimpleConditionElements();
		this.pObjectCondition = new ObjectConditionElements();
		this.pDistanceCondition = new DistanceConditionElements();
		this.pAngleCondition = new AngleConditionElements();
		this.eDETECTION = new DETECTIONElements();
		this.pMoveAction = new MoveActionElements();
		this.pTurnAction = new TurnActionElements();
		this.eDIRECTION = new DIRECTIONElements();
		this.eCAMERATYPE = new CAMERATYPEElements();
		this.pEDouble = new EDoubleElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.unice.polytech.si5.webots.Polycreate".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//RobotProgram:
	//	{RobotProgram}
	//	'RobotProgram'
	//	name=EString
	//	'->' initialState=State
	//	ownedStates+=State*
	//	globalTransitions+=Transition*;
	public RobotProgramElements getRobotProgramAccess() {
		return pRobotProgram;
	}
	
	public ParserRule getRobotProgramRule() {
		return getRobotProgramAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Condition:
	//	SimpleCondition | ObjectCondition;
	public ConditionElements getConditionAccess() {
		return pCondition;
	}
	
	public ParserRule getConditionRule() {
		return getConditionAccess().getRule();
	}
	
	//Action:
	//	MoveAction | TurnAction;
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}
	
	//Transition:
	//	{Transition} (conditions+=Condition ('and' conditions+=Condition)* '=>')? nextState=[State|EString];
	public TransitionElements getTransitionAccess() {
		return pTransition;
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}
	
	//State:
	//	{State}
	//	'State' name=EString
	//	':' ('actions' '=' '[' actions+=Action (',' actions+=Action)* ']')? ('transitions' '=' '[' transitions+=Transition
	//	("," transitions+=Transition)* ']')?;
	public StateElements getStateAccess() {
		return pState;
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}
	
	//SimpleCondition:
	//	{SimpleCondition}
	//	'detect' detectionType=DETECTION;
	public SimpleConditionElements getSimpleConditionAccess() {
		return pSimpleCondition;
	}
	
	public ParserRule getSimpleConditionRule() {
		return getSimpleConditionAccess().getRule();
	}
	
	//ObjectCondition:
	//	DistanceCondition | AngleCondition;
	public ObjectConditionElements getObjectConditionAccess() {
		return pObjectCondition;
	}
	
	public ParserRule getObjectConditionRule() {
		return getObjectConditionAccess().getRule();
	}
	
	//DistanceCondition:
	//	{DistanceCondition}
	//	'detect' 'object' cameraType=CAMERATYPE 'with' 'distance' '<' distance=EDouble;
	public DistanceConditionElements getDistanceConditionAccess() {
		return pDistanceCondition;
	}
	
	public ParserRule getDistanceConditionRule() {
		return getDistanceConditionAccess().getRule();
	}
	
	//AngleCondition:
	//	{AngleCondition}
	//	'detect' 'object' cameraType=CAMERATYPE 'with' 'angle' '<' angle=EDouble;
	public AngleConditionElements getAngleConditionAccess() {
		return pAngleCondition;
	}
	
	public ParserRule getAngleConditionRule() {
		return getAngleConditionAccess().getRule();
	}
	
	//enum DETECTION:
	//	COLLISION_LEFT | COLLISION_RIGHT | VIRTUAL_WALL | CLIFF_LEFT | CLIFF_RIGHT | CLIFF_FRONT;
	public DETECTIONElements getDETECTIONAccess() {
		return eDETECTION;
	}
	
	public EnumRule getDETECTIONRule() {
		return getDETECTIONAccess().getRule();
	}
	
	//MoveAction:
	//	{MoveAction}
	//	'move' direction=DIRECTION ('during' duration=EDouble)?;
	public MoveActionElements getMoveActionAccess() {
		return pMoveAction;
	}
	
	public ParserRule getMoveActionRule() {
		return getMoveActionAccess().getRule();
	}
	
	//TurnAction:
	//	{TurnAction}
	//	'turn' angle=EDouble ('during' duration=EDouble)?;
	public TurnActionElements getTurnActionAccess() {
		return pTurnAction;
	}
	
	public ParserRule getTurnActionRule() {
		return getTurnActionAccess().getRule();
	}
	
	//enum DIRECTION:
	//	FORWARD | BACKWARD;
	public DIRECTIONElements getDIRECTIONAccess() {
		return eDIRECTION;
	}
	
	public EnumRule getDIRECTIONRule() {
		return getDIRECTIONAccess().getRule();
	}
	
	//enum CAMERATYPE:
	//	BACK | FRONT;
	public CAMERATYPEElements getCAMERATYPEAccess() {
		return eCAMERATYPE;
	}
	
	public EnumRule getCAMERATYPERule() {
		return getCAMERATYPEAccess().getRule();
	}
	
	//EDouble ecore::EDouble:
	//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return pEDouble;
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
