/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.webots;

import fr.unice.polytech.si5.webots.AbstractPolycreateRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PolycreateRuntimeModule extends AbstractPolycreateRuntimeModule {
}
